# Ultralytics YOLO 🚀, AGPL-3.0 license

# Configuration file for building the Ultralytics YOLO documentation site using MkDocs.
# Provides settings to control site metadata, customize the appearance using the
# Material theme, define the navigation structure, and enable various plugins.

# Site metadata
site_name: mathhub
site_description: Explore Math World
site_url: https://nerbivol.github.io/mathhub/
site_author: nerbivol
repo_url: https://github.com/nerbivol/mathhub
edit_uri: https://github.com/nerbivol/mathhub/tree/main/docs/en/
repo_name: nerbivol/mathhub
remote_name:  https://github.com/nerbivol/mathhub/docs
docs_dir: "docs/en/" # where to find the markdown files
site_dir: "site/" # where to publish to

# Theme customization
theme:
  name: material
  language: en
  custom_dir: docs/overrides/
  logo: https://raw.githubusercontent.com/nerbivol/mathhub/bdf0894e4e6d82ad972da9ec094df4f779cc7436/docs/overrides/assets/logo_inver1-cropped.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  # font:  # disabled for faster page load times
  #  text: Helvetica
  #  code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

# Customization
copyright: <a href="https://nerbivol.github.io/mathhub/" target="_blank">© 2024 mathhub.</a> Template from <a href="https://ultralytics.com" target="_blank">Ultralytics Inc.</a> All rights reserved.
extra: # version:
  #   provider: mike  #  version drop-down menu
  robots: robots.txt
  analytics:
    provider: google
    property: G-2M5EHKC0BH
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nerbivol
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/serhii-biruk/

extra_css:
  - stylesheets/style.css
extra_javascript:
  - javascript/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: ./
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

# Validation settings https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

# Primary navigation ---------------------------------------------------------------------------------------------------
nav:
  - Головна:
      - Початок: index.md
      - Мови:
          - 🇺🇦&nbsp Українська: https://nerbivol.github.io/mathhub/
          - 🇬🇧&nbsp English: https://nerbivol.github.io/mathhub/en/
  - Елементи вищої алгебри:
      - Множини. Операції над множинами. Відображення множин. Потужність множин: algebra/sets.md
  - Tasks:
      - tasks/index.md
      - Detect: tasks/detect.md
      - Segment: tasks/segment.md
      - Classify: tasks/classify.md
      - Pose: tasks/pose.md
      - OBB: tasks/obb.md
  - Models:
      - models/index.md
      - YOLOv3: models/yolov3.md
      - YOLOv4: models/yolov4.md
      - YOLOv5: models/yolov5.md
      - YOLOv6: models/yolov6.md
      - YOLOv7: models/yolov7.md
      - YOLOv8: models/yolov8.md
      - YOLOv9: models/yolov9.md
      - YOLOv10: models/yolov10.md
      - SAM (Segment Anything Model): models/sam.md
      - MobileSAM (Mobile Segment Anything Model): models/mobile-sam.md
      - FastSAM (Fast Segment Anything Model): models/fast-sam.md
      - YOLO-NAS (Neural Architecture Search): models/yolo-nas.md
      - RT-DETR (Realtime Detection Transformer): models/rtdetr.md
      - YOLO-World (Real-Time Open-Vocabulary Object Detection): models/yolo-world.md
  - Datasets:
      - datasets/index.md
      - Detection:
          - datasets/detect/index.md
          - Argoverse: datasets/detect/argoverse.md
          - COCO: datasets/detect/coco.md
          - LVIS: datasets/detect/lvis.md
          - COCO8: datasets/detect/coco8.md
          - GlobalWheat2020: datasets/detect/globalwheat2020.md
          - Objects365: datasets/detect/objects365.md
          - OpenImagesV7: datasets/detect/open-images-v7.md
          - SKU-110K: datasets/detect/sku-110k.md
          - VisDrone: datasets/detect/visdrone.md
          - VOC: datasets/detect/voc.md
          - xView: datasets/detect/xview.md
          - Roboflow 100: datasets/detect/roboflow-100.md
          - Brain-tumor: datasets/detect/brain-tumor.md
          - African-wildlife: datasets/detect/african-wildlife.md
          - Signature: datasets/detect/signature.md
      - Segmentation:
          - datasets/segment/index.md
          - COCO: datasets/segment/coco.md
          - COCO8-seg: datasets/segment/coco8-seg.md
          - Crack-seg: datasets/segment/crack-seg.md
          - Carparts-seg: datasets/segment/carparts-seg.md
          - Package-seg: datasets/segment/package-seg.md
      - Pose:
          - datasets/pose/index.md
          - COCO: datasets/pose/coco.md
          - COCO8-pose: datasets/pose/coco8-pose.md
          - Tiger-pose: datasets/pose/tiger-pose.md
      - Classification:
          - datasets/classify/index.md
          - Caltech 101: datasets/classify/caltech101.md
          - Caltech 256: datasets/classify/caltech256.md
          - CIFAR-10: datasets/classify/cifar10.md
          - CIFAR-100: datasets/classify/cifar100.md
          - Fashion-MNIST: datasets/classify/fashion-mnist.md
          - ImageNet: datasets/classify/imagenet.md
          - ImageNet-10: datasets/classify/imagenet10.md
          - Imagenette: datasets/classify/imagenette.md
          - Imagewoof: datasets/classify/imagewoof.md
          - MNIST: datasets/classify/mnist.md
      - Oriented Bounding Boxes (OBB):
          - datasets/obb/index.md
          - DOTAv2: datasets/obb/dota-v2.md
          - DOTA8: datasets/obb/dota8.md
      - Multi-Object Tracking:
          - datasets/track/index.md
  - NEW 🚀 Solutions:
      - solutions/index.md
      - Analytics: guides/analytics.md
      - Object Counting: guides/object-counting.md
      - Object Cropping: guides/object-cropping.md
      - Object Blurring: guides/object-blurring.md
      - Workouts Monitoring: guides/workouts-monitoring.md
      - Objects Counting in Regions: guides/region-counting.md
      - Security Alarm System: guides/security-alarm-system.md
      - Heatmaps: guides/heatmaps.md
      - Instance Segmentation with Object Tracking: guides/instance-segmentation-and-tracking.md
      - VisionEye Mapping: guides/vision-eye.md
      - Speed Estimation: guides/speed-estimation.md
      - Distance Calculation: guides/distance-calculation.md
      - Queue Management: guides/queue-management.md
      - Parking Management: guides/parking-management.md
      - NEW 🚀 Live Inference: guides/streamlit-live-inference.md
  - Guides:
      - guides/index.md
      - YOLO Common Issues: guides/yolo-common-issues.md
      - YOLO Performance Metrics: guides/yolo-performance-metrics.md
      - YOLO Thread-Safe Inference: guides/yolo-thread-safe-inference.md
      - Model Deployment Options: guides/model-deployment-options.md
      - K-Fold Cross Validation: guides/kfold-cross-validation.md
      - Hyperparameter Tuning: guides/hyperparameter-tuning.md
      - SAHI Tiled Inference: guides/sahi-tiled-inference.md
      - AzureML Quickstart: guides/azureml-quickstart.md
      - Conda Quickstart: guides/conda-quickstart.md
      - Docker Quickstart: guides/docker-quickstart.md
      - Raspberry Pi: guides/raspberry-pi.md
      - NVIDIA Jetson: guides/nvidia-jetson.md
      - DeepStream on NVIDIA Jetson: guides/deepstream-nvidia-jetson.md
      - Triton Inference Server: guides/triton-inference-server.md
      - Isolating Segmentation Objects: guides/isolating-segmentation-objects.md
      - Edge TPU on Raspberry Pi: guides/coral-edge-tpu-on-raspberry-pi.md
      - Viewing Inference Images in a Terminal: guides/view-results-in-terminal.md
      - OpenVINO Latency vs Throughput modes: guides/optimizing-openvino-latency-vs-throughput-modes.md
      - ROS Quickstart: guides/ros-quickstart.md
      - Steps of a Computer Vision Project: guides/steps-of-a-cv-project.md
      - Defining A Computer Vision Project's Goals: guides/defining-project-goals.md
      - Data Collection and Annotation: guides/data-collection-and-annotation.md
      - Preprocessing Annotated Data: guides/preprocessing_annotated_data.md
      - Tips for Model Training: guides/model-training-tips.md
      - Insights on Model Evaluation and Fine-Tuning: guides/model-evaluation-insights.md
      - A Guide on Model Testing: guides/model-testing.md
      - Best Practices for Model Deployment: guides/model-deployment-practices.md
      - Maintaining Your Computer Vision Model: guides/model-monitoring-and-maintenance.md
      - Explorer:
          - datasets/explorer/index.md
          - Explorer API: datasets/explorer/api.md
          - Explorer Dashboard Demo: datasets/explorer/dashboard.md
          - VOC Exploration Example: datasets/explorer/explorer.ipynb

  - Help:
      - Help: help/index.md
      - Frequently Asked Questions (FAQ): help/FAQ.md
      - Contributing Guide: help/contributing.md
      - Continuous Integration (CI) Guide: help/CI.md
      - Contributor License Agreement (CLA): help/CLA.md
      - Minimum Reproducible Example (MRE) Guide: help/minimum_reproducible_example.md
      - Code of Conduct: help/code_of_conduct.md
      - Environmental, Health and Safety (EHS) Policy: help/environmental-health-safety.md
      - Security Policy: help/security.md
      - Privacy Policy: help/privacy.md

# Plugins including 301 redirects navigation ---------------------------------------------------------------------------
plugins:
  - search:
      lang: en
  - ultralytics:
      add_desc: False
      add_image: True
      add_authors: True
      add_json_ld: True
      add_share_buttons: True
      add_css: True
  - redirects:
      redirect_maps:
        package-framework.md: index.md
        package-framework/mock_detector.md: index.md
        predict.md: modes/predict.md
        quick-start.md: quickstart.md
        sdk.md: index.md
        tasks/classification.md: tasks/classify.md
        tasks/detection.md: tasks/detect.md
        tasks/segmentation.md: tasks/segment.md
        tasks/keypoints.md: tasks/pose.md
        tasks/tracking.md: modes/track.md
        SECURITY.md: help/security.md
        tutorials/nvidia-jetson.md: guides/nvidia-jetson.md
