# Ultralytics YOLO 🚀, AGPL-3.0 license

# Configuration file for building the Ultralytics YOLO documentation site using MkDocs.
# Provides settings to control site metadata, customize the appearance using the
# Material theme, define the navigation structure, and enable various plugins.

# Site metadata
site_name: mathhub
site_description: Explore Math World
site_url: https://nerbivol.github.io/mathhub/
site_author: nerbivol
repo_url: https://github.com/nerbivol/mathhub
edit_uri: https://github.com/nerbivol/mathhub/tree/main/docs/en/
repo_name: nerbivol/mathhub
remote_name:  https://github.com/nerbivol/mathhub/docs
docs_dir: "docs/en/" # where to find the markdown files
site_dir: "site/" # where to publish to

# Theme customization
theme:
  name: material
  language: uk
  custom_dir: docs/overrides/
  logo: https://raw.githubusercontent.com/nerbivol/mathhub/bdf0894e4e6d82ad972da9ec094df4f779cc7436/docs/overrides/assets/logo_inver1-cropped.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  # font:  # disabled for faster page load times
  #  text: Helvetica
  #  code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

# Customization
copyright: <a href="https://nerbivol.github.io/mathhub/" target="_blank">© 2024 Mathhub Inc.</a>
extra: # version:
  #   provider: mike  #  version drop-down menu
  robots: robots.txt
  analytics:
    provider: google
    property: G-Y3SBR6N7S8
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nerbivol
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/serhii-biruk/

extra_css:
  - stylesheets/style.css
extra_javascript:
  - javascript/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: ./
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

# Validation settings https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

# Primary navigation ---------------------------------------------------------------------------------------------------
nav:
  - Головна:
      - Початок: index.md
      - Мови:
          - 🇺🇦&nbsp Українська: https://nerbivol.github.io/mathhub/
          - 🇬🇧&nbsp English: https://nerbivol.github.io/mathhub/en/
  - Диференціальні рівняння:
      - Диференціальні рівняння першого порядку: differential/first_order.md
      - Однорідні диференціальні рівняння першого порядку: differential/homogeneous_first_order.md
      - Диференціальні рівняння, що зводяться до однорідних: differential/reducible_homogeneous_first_order.md


  - Вища алгебра:
      - Множини: algebra/sets.md




# Plugins including 301 redirects navigation ---------------------------------------------------------------------------
plugins:
  - search:
      lang: uk
  - ultralytics:
      add_desc: False
      add_image: True
      add_authors: True
      add_json_ld: True
      add_share_buttons: True
      add_css: True
  - redirects:
      redirect_maps:
#        differential_first_order.md: differential/first_order.md
#        package-framework/mock_detector.md: index.md
#        predict.md: modes/predict.md
#        sdk.md: index.md
#        tasks/classification.md: tasks/classify.md
#        tasks/detection.md: tasks/detect.md
#        tasks/segmentation.md: tasks/segment.md
#        tasks/keypoints.md: tasks/pose.md
#        tasks/tracking.md: modes/track.md
